### ISSUE TITLE
Latest fsnotify causes tests to hang

### ISSUE THREAD

**Issue by erbridge** [limetext/backend#86]
The issue appears to be caused by changes in [this commit](https://github.com/fsnotify/fsnotify/commit/e2532248b8b41873668e8e339833f9b4083d4a71). Not sure who is at fault.
##

**Comment by ricochet1k** [comment]
[goroutines.txt](https://github.com/limetext/lime-backend/files/208821/goroutines.txt)

This is referring to the goroutines.txt above

- goroutine 71: watch.Watch is holding the lock on lib/watch/watcher.go:95, waiting on flushDir waiting on watch.Remove waiting on fsnotify.Remove which is waiting for an ignore event through the Condition at inotify.go:158
- goroutine 8: the Observe event loop wants to send an event but the lock is being held already by goroutine 71 as above. The ignore event seems to be the after the one it is trying to handle.

Because Watch is holding the lock that the Observe loop wants to hold, if the events come out of order then fsnotify will be waiting to send another event and the Observe loop is stuck waiting for the lock, while the Watch holding the lock is waiting for another Ignore event.

**Comment by zoli** [comment]
related to https://github.com/fsnotify/fsnotify/issues/123.

**Comment by zoli** [comment]
This issue is causing a dead lock on `[TestSaveAsOpenFile](https://github.com/limetext/backend/blob/master/view_test.go#L199)`

**Comment by zoli** [comment]
After https://github.com/limetext/backend/commit/530bbfd0e08c282fae8710190eda4d8b5cd295f8 it seems there is no problem.
